//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListaArticulos
    {
        public int Registro_Articulo { get; set; }
        public string Codigo_Articulo { get; set; }
        public string Nombre_Articulo { get; set; }
        public string Pais_Origen { get; set; }
    }
}
